# Generated by Django 5.0 on 2025-04-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
