# Generated by Django 5.0 on 2025-04-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0002_usercollection_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='date_added',
        ),
        migrations.AddField(
            model_name='usercollection',
            name='card_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
