# Generated by Django 5.1.5 on 2025-04-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0003_remove_usercollection_card_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercollection',
            name='is_listed',
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='card_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usercollection',
            name='card_image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
