# Generated by Django 5.1.5 on 2025-04-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercollections', '0004_remove_usercollection_is_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
