# Generated by Django 5.1.5 on 2025-04-30 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='highest_bid',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='highest_bidder',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='pokemon_name',
        ),
        migrations.AddField(
            model_name='auction',
            name='card_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='card_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='card_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
