# Generated by Django 5.1.5 on 2025-04-30 02:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward', models.IntegerField(default=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AlterField(
            model_name='userchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challengetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='userchallenge',
            unique_together={('user', 'challenge')},
        ),
        migrations.DeleteModel(
            name='Challenge',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='date_assigned',
        ),
    ]
