# Generated by Django 5.1.5 on 2025-04-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challengetemplate_alter_userchallenge_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
