# Generated by Django 5.1.5 on 2025-04-30 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='is_active',
            new_name='is_trade',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='current_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='card_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='card_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ListingBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='marketplace.listing')),
            ],
            options={
                'ordering': ['-amount', 'placed_at'],
            },
        ),
    ]
