# Generated by Django 5.1.5 on 2025-04-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_claimed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
