# Generated by Django 5.0 on 2025-04-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_last_daily_pack_claim_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_daily_pack_claim',
        ),
        migrations.AlterField(
            model_name='profile',
            name='currency_balance',
            field=models.IntegerField(default=1000),
        ),
    ]
